// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarManagement.Data;

#nullable disable

namespace SolarManagement.Migrations
{
    [DbContext(typeof(SolarManagementContext))]
    [Migration("20240407130154_InitialCommit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SolarManagement.Models.powertbl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<decimal>("Ampere")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("datetimecreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("power")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("volt")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("id");

                    b.ToTable("powertbl");
                });
#pragma warning restore 612, 618
        }
    }
}
